### ISSUE TITLE
Can't unlock account

### ISSUE THREAD

**Issue by Endogen** [idena-dev/idena-pocket#16] opened 2020-04-19 19:21 UTC
On https://pocket.idena.dev with Safari or Chrome, if i create a new wallet and then try to login, i get the "Unlocking account" screen but then it just stays there. I can't unlock the account. Refreshing the site doesn't help.
![image](https://user-images.githubusercontent.com/226475/79697549-b9ef0f00-8283-11ea-8156-a8623f8f977c.png)

**Comment by Gutalean** [comment] 2020-04-19 22:14
Same here.

**Comment by menxit** [comment] 2020-04-20 05:55
Is it possible you tried to unlock the wallet when api.idena.org or rpc.idena.dev were down? Can you check to be able to retrieve info using these curls? If so, retry to unlock the wallet.
```
curl https://api.idena.org/api/Address/0x62449c9b1029db6df55ecf215d0aaa0cea23c66d/Txs?skip=0&limit=30
```
```
curl -X POST -H 'content-type:application/json;' https://rpc.idena.dev --data @- << EOF
{
	"method": "bcn_syncing",
	"id": 2
}
EOF
```

However we should manage this state. For example we could show an error toast on timeout, something like:"api.idena.org seems to be down, retry later."

**Comment by Endogen** [comment] 2020-04-20 10:31
Nope, doesn't work. Tried on a Windows 10 machine and on a Ubuntu Server. Same on both systems:

```
0
404 page not found
```

and thus also the same error with the wallet.

**Comment by bingbinglee** [comment] 2020-04-20 13:15
@Endogen just tried on pocket.idena.dev and it seems to work okay for me. could not reproduce this. Maybe @menxit already fixed it?

**Comment by bingbinglee** [comment] 2020-04-20 13:39
@menxit 
Was able to reproduce this error. When I tried importing an old wallet on pocket, it worked fine and unlocked the account.

But when I created a new wallet on pocket, it does not work. Try creating a new wallet instead of importing one through mnemonic. I didn't understand the issue correctly before.

**Comment by menxit** [comment] 2020-04-20 17:01
Bug fixed.
If you want to retry you should:
1. Reset localstorage clicking on "Use a different wallet"
2. Recreate a wallet clicking on "Create wallet"
3. Retry to login

Otherwise, if you want to recover the generated seed:
1. CTRL+ALT+J > Application > localstorage > https://pocket.idena.dev
2. Set as "derivation_path" value "m/44'/515'/0'/0/0"

When someone confirm me that now it works, I'll close this issue.

**Comment by bingbinglee** [comment] 2020-04-20 17:51
Worked for me. 
I would wait for @Endogen to reply if he is also able to do this now. 

@menxit what was the bug about? want to post what the fix contained?

**Comment by menxit** [comment] 2020-04-20 17:55
Yep, you can find diff here:
https://github.com/idena-dev/idena-pocket/commit/14c0cfcf89089e7ac71aa6bfd3dcf675644c13af

It didn't save default derivation path ("m/44'/515'/0'/0/0") in localstorage.

**Comment by Endogen** [comment] 2020-04-21 10:26
Yesterday it seemed to work but today i did another test and it didn't work. Again same issue but now with an already created wallet. I can't login, message `Unlocking account` just stays there.

**Comment by bingbinglee** [comment] 2020-04-21 13:47
@Endogen tried again. it seems like the API endpoints were down at the time of when you were trying to log in. I have tried again both via import, creating a new wallet and login with existing ones and it seemed to have worked fine. 

I will be opening an issue related to this based on @menxit suggestion.

**Comment by bingbinglee** [comment] 2020-04-21 13:49
#26

**Comment by Endogen** [comment] 2020-04-21 21:01
Just checked again. Same situation. This can't be an endpoint issue?

**Comment by menxit** [comment] 2020-04-22 21:09
I talked with @Endogen and seems a something linked with its particular localstorage state. [This](https://github.com/idena-dev/idena-pocket/commit/14c0cfcf89089e7ac71aa6bfd3dcf675644c13af), resolved the issue.

**Closed by menxit** 2020-04-22 21:09 UTC
Labels: bug
